### ISSUE TITLE
Gather full test data from each workflow run

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#11]
Gather data about each test run, including retries, within a single workflow. All this data can be found in the json files downloaded from GH.

- name
- workflow run id (key in a different table)
- configuration (memtx, vinyl and so on)
- test-run worker number
- success/failure (separate record for each retry)

**Comment by Totktonada** [comment]
Workflow retries are handled properly:

https://github.com/tarantool/multivac/blob/49f325d7219ec4235dbf4768c821f5b9c87cf5fe/multivac/fetch.py#L337-L358

But it was implemented before individual job restart support was land on GitHub, so it worth to re-check.
