### ISSUE TITLE
Show a table with all failed tests, filtered by dashboard's variables

### ISSUE THREAD

**Issue by Totktonada** [tarantool/multivac#2]
On the test dashboard, show a table with all test results, including links to workflows and saved data & logs. Use pagination for long tables.

Example: table showing results for app-luatest/gh_5747_crash_multiple_args_test

| test name                                    | job_name | commit_sha | GH job link | workflow.json link | job.json link | job.log link |
|----------------------------------------------|----------|------------|-------------|--------------------|---------------|--------------|
| app-luatest/gh_5747_crash_multiple_args_test | coverage | abcde12    | job run     | workflow.json      | job.json      | job.log      |
| app-luatest/gh_5747_crash_multiple_args_test | debug    | abcde12    | job run     | workflow.json      | job.json      | job.log      |
| app-luatest/gh_5747_crash_multiple_args_test | coverage | 98fe654    | job run     | workflow.json      | job.json      | job.log      |

---
(original text)

last_seen: no way to look at all logs

The table contains only one link to a log per test, but sometimes we want to look at all logs to understand, whether fails appear due to the same problem or because of different ones.

**Comment by NickVolynkin** [comment]
@Totktonada we're rebuilding the whole system with a database, see #7 and #23 in particular. With all this, will you still need the full list of links somewhere on a website?

**Comment by Totktonada** [comment]
If I'm investigating a problem with a test, I want to look on all existing fails. Whether it will be in the 'last_seen' report or in another one, which will be implemented in a future, does not matter for me.

**Comment by NickVolynkin** [comment]
@Totktonada I've reworded this task. The table will be a part of the test analysis dashboard in our Grafana.

**Comment by Totktonada** [comment]
Thank you for working on it! I don't mind the new definition of the task.

**Comment by lastoCHka42** [comment]
https://mon.tarantool.io/grafana/d/vQ35ub74k/test-statistics?orgId=1&var-bucket=multivac-tests&var-job_name=All&var-test_name=All&var-tag=gc64&var-configuration=none&viewPanel=6

**Comment by lastoCHka42** [comment]
Because it is too many sp to make multivalue table, with @NickVolynkin decided to make this table as an html-page at the `shame` website.

Steps for this way: 
- [ ] Add new function to store test data as a CSV file (`failed_tests.csv`). Executes when option `--test-csv` set.
- [ ] Add an entry point to the tests page on the `crawler` page
- [ ] Create a `tests.html` to process `failed_tests.csv) like `index.html` processes `last_seen.csv`
