### ISSUE TITLE
Put workflow data to the database

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#23]
Store workflow data from #10 and #22 in a database.

Workflow id should probably be the index, because we'll bind specific test results to their workflows in #11 and #24.

It is highly likely that we'll sometimes re-parse raw data to get improved data. In such case we'll rewrite this data.

Note that a workflow can have re-runs. All re-runs should be stored separately. 

## Definition of done
1. We have code that puts workflow data to InfluxDB (no matter can we build a dashboard or not)
2. We have a document how to set up and connect to a local InfluxDB

**Comment by lastoCHka42** [comment]
# Design document
We choosed InfluxDB to be able write informative graphics. So I've decided to use future graphic as a starting point.

First of all, what do we need:
1. Install influxdb-client (insert it to `requirements.txt)
2. Import library in python code: `from ifluxdb-client import InfluxDBClient`
4. Connect to DB (see below)
5. Collect and write neccessary data
