### ISSUE TITLE
Keep crawler website code in the repo, deploy with CI/CD

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#32]
Crawler website's code is stored on the server only. It's not the right way to work with code.

- [ ] Website's code is kept in a git repository. Can be tarantool/multivac or some other.
- [ ] Deploy page from master branch with code.
- [ ] Deploy to test environment with code. (There can

**Comment by lastoCHka42** [comment]
We don't support crawler anymore, all the functional is in the table on Grafana dashboard
