### ISSUE TITLE
Detect test type, arch, OS, gc/nogc

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#51]
Detect test type, send it to InfluxDB as tag:

- luatest
- TAP
- diff
- SQL (subtype of diff)
- Python (subtype of diff)

(list confirmed by @Totktonada)

Detect other parameters:

- architecture: x86_64 or aarch64
- debug/release build
- OS (name and version)
- gc64 / nogc64
- branch (`1.10`, `2.10`, `master`; feature branches will be added later).

**Comment by lastoCHka42** [comment]
- [ ] test type
- [ ] debug/release
- [ ] OS name and version
- [ ] gc64/nogc
- [ ] branch
- [ ] architecture
