### ISSUE TITLE
Gather compiler version, glibc version

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#84]
Gather extra tags:

- Compiler name and version (as one tag, like OS and version)
- glibc version up to the second number (like `2.30`). We can assume that version is defined for each distributive and doesn't change.

**Comment by lastoCHka42** [comment]
> * We can assume that version is defined for each distributive and doesn't change.

In this case, we can don't add new tags to InfluxDB, just add a panel with remap OS version with glibc version
